# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_yZZcWnKTm_CzHd-P4fF0w9tWVVCU0S5
"""

# save as transformer_sepsis_app.py
import streamlit as st
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, Model

# --------------------------
# Synthetic Data Generator
# --------------------------
def generate_patient(hours=48, septic=False):
    t = np.arange(hours)
    HR = np.random.normal(85, 10, hours)
    MAP = np.random.normal(75, 8, hours)
    Temp = np.random.normal(37, 0.5, hours)
    RR = np.random.normal(18, 4, hours)
    Lactate = np.random.normal(1.6, 0.4, hours)
    HR += np.random.normal(0, 0.05) * t
    MAP += np.random.normal(0, 0.05) * t
    if septic:
        onset = np.random.randint(12, 36)
        severity = np.random.uniform(0.3, 0.8)
        HR[onset:] += severity * np.linspace(0, 10, hours-onset)
        MAP[onset:] -= severity * np.linspace(0, 8, hours-onset)
        Temp[onset:] += severity * np.linspace(0, 2, hours-onset)
        RR[onset:] += severity * np.linspace(0, 6, hours-onset)
        Lactate[onset:] += severity * np.linspace(0, 4, hours-onset)
    HR += np.random.normal(0, 2, hours)
    MAP += np.random.normal(0, 2, hours)
    Temp += np.random.normal(0, 0.2, hours)
    RR += np.random.normal(0, 1, hours)
    Lactate += np.random.normal(0, 0.3, hours)
    return np.vstack([HR, MAP, Temp, RR, Lactate]).T

# Generate dataset
N, H, F = 200, 48, 5  # smaller for app
X, y = [], []
for i in range(N):
    septic = np.random.rand() < 0.35
    X.append(generate_patient(H, septic))
    y.append(int(septic))
X = np.array(X, dtype=np.float32)
y = np.array(y, dtype=np.float32).reshape(-1,1)

# --------------------------
# Transformer Model Definition
# --------------------------
def positional_encoding(seq_len, d_model):
    angle_rads = np.arange(seq_len)[:, np.newaxis] / np.power(
        10000, (2 * (np.arange(d_model)[np.newaxis, :] // 2)) / np.float32(d_model)
    )
    angle_rads[:, 0::2] = np.sin(angle_rads[:, 0::2])
    angle_rads[:, 1::2] = np.cos(angle_rads[:, 1::2])
    return tf.cast(angle_rads[np.newaxis, ...], dtype=tf.float32)

def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout=0.1):
    x = layers.MultiHeadAttention(num_heads=num_heads, key_dim=head_size)(inputs, inputs)
    x = layers.Dropout(dropout)(x)
    x = layers.LayerNormalization(epsilon=1e-6)(x + inputs)
    x_ff = layers.Dense(ff_dim, activation='relu')(x)
    x_ff = layers.Dense(inputs.shape[-1])(x_ff)
    x = layers.LayerNormalization(epsilon=1e-6)(x + x_ff)
    return x

def build_transformer(input_shape, head_size=32, num_heads=2, ff_dim=64, num_blocks=2, dropout=0.1):
    inputs = layers.Input(shape=input_shape)
    x = inputs + positional_encoding(input_shape[0], input_shape[1])
    for _ in range(num_blocks):
        x = transformer_encoder(x, head_size, num_heads, ff_dim, dropout)
    x = layers.GlobalAveragePooling1D()(x)
    x = layers.Dropout(0.2)(x)
    x = layers.Dense(32, activation='relu')(x)
    x = layers.Dropout(0.2)(x)
    outputs = layers.Dense(1, activation='sigmoid')(x)
    return Model(inputs, outputs)

# --------------------------
# Build and train a small model
# --------------------------
model = build_transformer(input_shape=(H, F))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['AUC'])
model.fit(X, y, epochs=5, batch_size=16, verbose=0)  # small epochs for demo

# --------------------------
# Streamlit App
# --------------------------
st.title("Sepsis Risk Prediction - Transformer")

patient_idx = st.slider("Select Patient ID", 0, N-1, 0)
patient_data = X[patient_idx]

st.write(f"True label: {'Sepsis' if y[patient_idx][0]==1 else 'No Sepsis'}")

# Plot vitals
df = pd.DataFrame(patient_data, columns=["HR","MAP","Temp","RR","Lactate"])
st.line_chart(df)

# Predict probability
risk_prob = model.predict(patient_data[np.newaxis, ...])[0,0]
st.metric("Predicted Sepsis Probability", f"{risk_prob:.2f}")